from Bio import SeqIO # to parse sequence data

import io # to convert string to 'handle'

handle = open("seqs.fa", "r")
handle = handle.read()
handle = io.StringIO(handle)

# parse sequences in 'fasta' format; this returns an iterator, which stores
# a sequence of elements
sequences = SeqIO.parse(handle, "fasta")

# each sequence is stored as a SeqRecord object
# http://biopython.org/DIST/docs/tutorial/Tutorial.html#sec:seq_features

# EL 3, 1, 2 SEQ: AATTGAGGTGGATCGGTGGATCGGTGGATCAGTTCATTTCGGAACTGAAATGAGCCGTGTCCGAGGTGAGTCCGGAAATGGGCTCAAAACTGCGGTGAAACCACTGACATCCGGACAGCGTTGCGACAGTGGCGCTTTTAGCGCAGCCCGGGGGTTTTTACAGGATACC

num = 1
target_seq = "TTATGAAGGACTATGGAGCTGATGATTTCGAAATGAAAACGGATGCCTTTGAAGGGATAGAAACGGGTGGGAAGAAAGTGAGTCGCGTCCGTTGTTGCGGGAAGACAGACGAAACAAGCAGCTAATGGCATGGTGTAGGTATTACTGATGGATGATCTTTTGGGAAAGGGCGGAAGTATCATGGCTGCCAAAGGGGTGAGTAAAGGAAGGCCTTCCCTATCCTACATCCACGCTGTCTCCTTGCAAACAGACAGACGGACTGTAACGAACAACTGCTTGCTAACCATTCCCCAGCTCTGCGAAAAACTAAACGTCAAAGTCGCAGAAGCGATCTTCATATTCGACTGCGACGGCGTCCCGGGCTACCAGCAGACCGTCAACAAGACTCTAGGTGGTCTGAAGAGATACGCCATGATCACATTATCAACTTCGAATATCGGGGCGCCTGTAAATTGAATACCAATTCTCTTCACTTCACGCTTGACTCTCTCTTGAGCATTGAGAATTAAGCAACTACACTTCTCTGCCTCATTCCCCTCAGGCCAAACATGTTAATAATATCCCTCATATCAAGCTTGGTAGCAAGGACTAGATATATAGATATATAGTTTCTACTACTACTGTGTAGTACTATAGAAAACCCCGCTCTCATATACCCCCCAACCCCCAAGCACCACGCTCTCCAACTCCAAGCACCACGCTCTCCATCTCCAAGCATCACCCTCCCTAGTCCCCAACTCTCCTATTACTGTGTACACCCTTCCCCATACAAGGCTCACCCCATCAACTCCCCAACAACTATCCCTCCTCACCCCCCATCCCCGCGTCTGCGGTAATCAAAACTCTACTATTCCTAGTTTCCTATTCCTATCCCCTTCCCCAACAAGGCCCAAGGTCC"
target_seq_len = len(target_seq)

# loop through sequence records in the file
for s in sequences:
    print(s.seq)
    #print(s.seq.reverse_complement())

    hit_pos = s.seq.find(target_seq)
    if (hit_pos != -1) : 
        print("SAMPLE: " + s.id)
        print("POSITION: " + str(hit_pos))
        if hit_pos + target_seq_len + 200 < len(s.seq):
            print("UPSTREAM: " + s.seq[hit_pos + target_seq_len + 200::])
    num = num + 1
    if num == 5 :
        break
